from .dior import *
from .etci2021 import *
from .kenya_croptype import *
from .bigearthnetv2 import *
from .dfc2022 import *
from .caffe import *
from .minifrance import *
from .base import *
from .sen12ms import *