# lightning.pytorch==2.1.1
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: bf16
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: experiments
      name: eurosat
  callbacks:
    - class_path: TQDMProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch

  max_epochs: 10
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  enable_checkpointing: true
  default_root_dir: experiments
data:
  class_path: torchgeo.datamodules.EuroSATDataModule
  init_args:
    batch_size: 64
    num_workers: 0
    bands: ["B04", "B03", "B02"]
  dict_kwargs:
    root: data/eurosat

model:
  class_path: terratorch.tasks.ClassificationTask
  init_args:
    model_factory: EncoderDecoderFactory
    model_args:
      backbone: timm_convnextv2_atto
      backbone_pretrained: True
      decoder: IdentityDecoder
      num_classes: 10
    # loss: mse
    ignore_index: -1
    freeze_backbone: false
    freeze_decoder: false 

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1.e-4
    weight_decay: 0.1
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val/loss